[package]
name = "rust-app-rust-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-plugin-rust-test = "0.3.4"